# Generated by Django 4.1.3 on 2022-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
